### ISSUE TITLE
Implementing new UI for the client

### ISSUE THREAD

**Issue by DieGurke** [informatik-ag-ngl/envoy#16]

**Comment by delvh** [comment]
Wow. Never before have I seen such a glorious case of egomania.
I'd understand it if you provided a description of what you want to have changed and then changed it yourself.
But no, the fine gentleman opens an issue without any description jut so that he can be the one who fixes it.
But seriously, **learn to provide descriptions for your issues**, otherwise I'll mark them as `wontfix`

**Comment by DieGurke** [comment]
No I won't you "fine gentleman" as it was clear from the beginning on, that I will work on this issue. (There is a reason the assignees section exists)

**Comment by delvh** [comment]
That does not change anything for the underlying problem: An issue should, when it's a feature request, contain the actions to be taken. It does not need to be complete (you can update it over time), however **it should contain the description of what you want implemented**.
Otherwise I'll open an issue "End World hunger" without description and assign only you. Do you want that?
Would you know in this case how you could fix it? No, because it does not provide hints on what should be done.
